### ISSUE TITLE
php-http/adapter

### ISSUE THREAD

**Issue by sagikazarmark** [kbond/ZenstruckCacheBundle#11]
Hey there,

I am sure you noticed that php-http/adapter has been abandoned and renamed to httplug. Your package still relies on the old package which will be removed in a few weeks meaning your package will be uninstallable. Please make sure that you update/remove that dependency.

For more details see this issue: php-http/httplug#101

**Comment by kbond** [comment]
Thanks Mark, I already have a PR open #9. I am just waiting until httplug is stable before I finalize and merge.

**Comment by sagikazarmark** [comment]
Okay. We hope to release a stable version in January, currently we are implementing HTTPlug in packages which rely on some kind of HTTP client maintained by "us" (the core team).

**Comment by sagikazarmark** [comment]
HTTPlug is now stable.

**Comment by kbond** [comment]
Thanks, I will work on finalizing the PR.
